# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: oc-setup@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OCP Cluster'
    version: '4.6'

- task: Bash@3
  inputs:
    filePath: 'tree'
    
# - task: oc-cmd@2
#   inputs:
#     connectionType: 'OpenShift Connection Service'
#     openshiftService: 'OCP Cluster'
#     cmd: 'oc apply -f openshift/app/bc-s2i.yaml -n liferay'
# - task: oc-cmd@2
#   inputs:
#     connectionType: 'OpenShift Connection Service'
#     openshiftService: 'OCP Cluster'
#     version: '4.8'
#     cmd: 'oc apply -f openshift/app/deployment.yaml'