apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: spring-boot-helloworld
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: spring-boot-helloworld
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "spring-boot-helloworld:latest"
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: "DockerImage"
        name: "image-registry.openshift-image-registry.svc:5000/openshift/ubi8-openjdk-8:1.3"
  triggers:
    - type: ConfigChange
