apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
    version: v1
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: {{ .Values.appName }}
