# Default values for helm-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: helm-spring-boot-helloworld
replicaCount: 1

image:
  repository: spring-boot-helloworld
  tag: latest

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 256Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
