apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
    version: v1
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
spec:
  replicas: {{  .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        version: v1
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8778
            name: jolokia
          - containerPort: 8080
            name: http 
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
        # resources: 
        #   limits: 
        #     cpu: 100m
        #     memory: 128Mi
        # requests:
        #   cpu: 100m
        #   memory: 128Mi

