apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    {{- include "helloworld-springboot.labels" . | nindent 4 }}
spec:
  replicas: {{  .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      version: v1
  template:
    metadata:
      labels:
        {{- include "helloworld-springboot.labels" . | nindent 8 }}
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{ end }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8778
            name: jolokia
          - containerPort: 8080
            name: http 
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10