apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: mvn-binary-pipelinerun
spec:
  serviceAccountName: pipeline 
  pipelineRef:
    name: mvn-binary-pipeline
  resources: 
    - name: git-oc-two
      resourceSpec: 
        type: git 
        params: 
          - name: revision 
            value: master 
          - name: url 
            value: https://github.com/DaniellaFreese/spring-boot-helloworld.git
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec: 
        accessModes: 
          - ReadWriteOnce 
        resources:
          requests:
            storage: 1Gi
  - name: maven-settings 
    emptyDir: {}
  - name: images-url 
    emptyDir: {}  
  params: 
    - name: GIT_URL
      value: https://github.com/DaniellaFreese/spring-boot-helloworld.git
    - name: IMAGE 
      value: spring-boot-helloworld
    - name: TAG 
      value: "latest"
    - name: NAMESPACE
      value: "danny"